### ISSUE TITLE
long discriptions break install ui

### ISSUE THREAD

**Issue by unmellow** [excalibur1234/pacui#61] opened 2021-01-26 03:30 UTC
I installed and tested pacui and pacui-git
from manjaro community
found this bug in both but the one being displayed is 
pacui-git-1.14.r6.g846f892-1

I initially found this bug while testing my fork which is from master
so I'm pretty sure it is still their

![2021-01-25T22:21:17,049134462-05:00](https://user-images.githubusercontent.com/30985587/105795932-b21f7200-5f5b-11eb-9229-e6cedd1b9979.png)
![2021-01-25T22:21:10,569162832-05:00](https://user-images.githubusercontent.com/30985587/105795933-b21f7200-5f5b-11eb-8bfd-b6e455f73e71.png)
![2021-01-25T22:20:55,592891707-05:00](https://user-images.githubusercontent.com/30985587/105795935-b2b80880-5f5b-11eb-8ceb-9ef55a577e76.png)
![2021-01-25T22:20:36,209541351-05:00](https://user-images.githubusercontent.com/30985587/105795936-b2b80880-5f5b-11eb-8ed4-b86eb8cd9ae1.png)
![2021-01-25T22:20:12,759310565-05:00](https://user-images.githubusercontent.com/30985587/105795938-b2b80880-5f5b-11eb-94b0-7508564a36e5.png)

**Comment by excalibur1234** [comment] 2021-02-27 10:54
i have reproduced the bug, despite being a little elusive.

it only appears, when i have entered a search string.
it disappears, when i change my terminal width (and reappears in other lines).

i report back, when i have more information.

**Comment by excalibur1234** [comment] 2021-02-27 11:33
i have narrowed it down to a bug in the search result display of fzf:
the follow command in your terminal is enough to reproduce this bug:
`expac -S "%-33n\t%d" | fzf --preview 'echo text'  `
now, search for a string, e.g. "e" and scroll to search results with long description texts (e.g. by holding down your PageUp key).

can you reproduce this behavior?

strangely enough, the search result page of fzf seems to be arranged by total sting length. 
however, it seems to be broken, because when i scroll through the entire search result list, i can see 2 parts. both are arranged by total string length.
only one part/block seems to produce this bug.

**Comment by excalibur1234** [comment] 2021-02-27 11:39
i do not see any way i can fix this bug (besides removing the preview window completely, which i am not willing to do).

feel free to further investigate this bug.
you can start with the command i have given above.
maybe certain symbols (e.g. newlines, tabs, or spaces) within some description strings causes this bug.
then, you can report it upstream (i.e. here: https://github.com/junegunn/fzf)

when you do this, feel free to link this issue.

**Comment by excalibur1234** [comment] 2021-02-28 09:32
after some more testing, i think i have found a solution.

on my system using the following command (as described 2 posts above) results in this bug:
`expac -S "%-33n\t%d" | fzf --preview 'echo text' `
however this command does NOT show the bug:
`expac -S "%-33n    %d" | fzf --preview 'echo text' `

it seems the tab (i.e. "\t" in the printf statement) symbol causes this bug.

can you confirm this behavior?

if your system also shows this bug only with one of the commands above, i can actually fix this bug.

**Comment by unmellow** [comment] 2021-03-01 21:19
yes this command 
```sh
expac -S "%-33n %d" | fzf --preview 'echo text'
```
doesn't appear to have the bug
the examples i found render correctly now

**Comment by excalibur1234** [comment] 2021-03-03 20:54
fixed in 195d8f59277399b9a0b730123840532cc4900229

thanks for working with me to resolve this bug!

**Closed as completed by excalibur1234** 2021-03-03 20:54 UTC
